### ISSUE TITLE
[3.9] As a host, I want to be able to reset the lobby so I can quickly play another game without sending out fresh invites. 

### ISSUE THREAD

**Issue by ckulbaski** [dietterc/SEO-ker#23]
Acceptance criteria: I am able to quickly play another game without sending out new invites

Priority: Low  

Estimated length: Short-medium

**Comment by dietterc** [comment]
Moved to feature 3 since this will only happen once a game is completed. 
Players will start in a lobby, move to a game object, then once the game is over 'reset' the lobby so people can leave/join
